velocity_controllers:
  update_rate: 100 # Hz
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster
  joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      # Thêm tất cả các khớp cần điều khiển ở đây
    constraints:
      goal_time: 2.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.4
      joint1:
        trajectory: 0 
        goal: 0.2       
      joint2:
        trajectory: 0 
        goal: 0.2       
      joint3:
        trajectory: 0 
        goal: 0.2       
      joint4:
        trajectory: 0 
        goal: 0.2       
      joint5:
        trajectory: 0 
        goal: 0.2       
      joint6:
        trajectory: 0 
        goal: 0.2       
    interface_name: velocity

    command_interfaces:
      - velocity
    
    state_interfaces:
      - position
      - velocity
    gains:
      joint1: {p: 1000.0,  i: 0.1, d: 1.0, i_clamp: 1}
      joint2: {p: 1000.0,  i: 0.1, d: 1.0, i_clamp: 1}
      joint3: {p: 1000.0,  i: 0.1, d: 1.0, i_clamp: 1}
      joint4: {p: 1000.0,  i: 0.1, d: 1.0, i_clamp: 1}
      joint5: {p: 1000.0,  i: 0.1, d: 1.0, i_clamp: 1}
      joint6: {p: 1000.0,  i: 0.1, d: 1.0, i_clamp: 1}

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
